"""Synthetic Investigation Dataset Generator for Network Hunter PS09 demonstration.

Contains:
- Primary case: CASE-001 (Operation Meridian)
- Secondary case: CASE-002 (Meridian Financial Link)
- 13 Person entities (including edge cases: duplicate name, multiple phones)
- 3 Organization entities
- 4 Phone entities
- 4 Account entities (including shared account pattern)
- 3 Vehicle entities
- 5 Location entities
- 3 Device entities
- 2 Case entities
- 35+ Relationships with full provenance
- 22+ Events (call -> meeting -> transaction sequence, expansion timeline)
- 25+ Sources
- 25+ Evidence records with synthetic labeling
"""

from datetime import datetime, timezone

# Standard metadata for all synthetic records
SYNTHETIC_METADATA = {
    "data_origin": "SYNTHETIC",
    "demo_only": True,
    "classification": "UNCLASSIFIED // DEMO BENCHMARK",
    "notice": "Synthetic Data — For Demonstration Only",
}


def get_synthetic_dataset():
    """Generates the full demonstration dataset structure."""
    
    # --- 1. CASES ---
    cases = [
        {
            "id": "CASE-001",
            "case_number": "NH-2026-001",
            "title": "Operation Meridian",
            "description": "Cross-border investigation into coordinated transnational wire transfers, shell companies, and illicit logistics operations centered around Metro Harbor.",
            "status": "ACTIVE",
            "priority": "HIGH",
            "created_at": datetime(2026, 1, 5, 8, 0, 0, tzinfo=timezone.utc),
            "updated_at": datetime(2026, 3, 20, 16, 30, 0, tzinfo=timezone.utc),
        },
        {
            "id": "CASE-002",
            "case_number": "NH-2026-002",
            "title": "Meridian Financial Link",
            "description": "Targeted forensic financial probe into offshore escrow routing, nominee banking accounts, and intermediary conduits connected to Apex Holdings.",
            "status": "REVIEW",
            "priority": "MEDIUM",
            "created_at": datetime(2026, 3, 1, 9, 15, 0, tzinfo=timezone.utc),
            "updated_at": datetime(2026, 3, 22, 11, 0, 0, tzinfo=timezone.utc),
        },
    ]

    # --- 2. ENTITIES ---
    entities = [
        # PERSONS (13)
        {
            "id": "P-001",
            "entity_type": "PERSON",
            "name": "Marcus Vance",
            "description": "Primary subject of interest; suspected coordinator of logistics and financial disbursements.",
            "status": "ACTIVE",
            "attributes": {"dob": "1982-04-14", "nationality": "US", "risk_score": 0.92, "alias": "The Architect"},
        },
        {
            "id": "P-002",
            "entity_type": "PERSON",
            "name": "David Vance",
            "description": "Elder brother of Marcus Vance; director of operations at Meridian Logistics.",
            "status": "ACTIVE",
            "attributes": {"dob": "1979-11-22", "nationality": "US", "risk_score": 0.78, "role": "Operations Manager"},
        },
        {
            "id": "P-003",
            "entity_type": "PERSON",
            "name": "Elena Rostova",
            "description": "Financial broker and offshore trustee; authorized signatory on Apex Holdings accounts.",
            "status": "ACTIVE",
            "attributes": {"dob": "1985-07-03", "nationality": "CH", "risk_score": 0.88, "specialty": "Structured Finance"},
        },
        {
            "id": "P-004",
            "entity_type": "PERSON",
            "name": "Julian Thorne",
            "description": "Intermediary facilitator connecting logistics and cross-border financial transactions. Key link between CASE-001 and CASE-002.",
            "status": "ACTIVE",
            "attributes": {"dob": "1988-09-17", "nationality": "UK", "risk_score": 0.85, "alias": "J. T."},
        },
        {
            "id": "P-005",
            "entity_type": "PERSON",
            "name": "Sophia Chen",
            "description": "Senior compliance officer at Apex Holdings Ltd; internal whistleblower / person of interest.",
            "status": "ACTIVE",
            "attributes": {"dob": "1990-02-11", "nationality": "US", "clearance": "Internal Auditor"},
        },
        {
            "id": "P-006",
            "entity_type": "PERSON",
            "name": "Viktor Ramos",
            "description": "Former fleet transport manager at Meridian Logistics (left firm Nov 2025).",
            "status": "INACTIVE",
            "attributes": {"dob": "1980-05-30", "nationality": "MX", "employment_status": "Terminated"},
        },
        {
            "id": "P-007",
            "entity_type": "PERSON",
            "name": "Tariq Mansoor",
            "description": "Independent accountant managing invoicing records for Vanguard Trade Corp.",
            "status": "ACTIVE",
            "attributes": {"dob": "1984-12-08", "nationality": "CA", "license": "CPA-7721"},
        },
        {
            "id": "P-008",
            "entity_type": "PERSON",
            "name": "Clara Bennett",
            "description": "Corporate attorney representing Meridian Logistics and Marcus Vance.",
            "status": "ACTIVE",
            "attributes": {"dob": "1976-08-19", "nationality": "US", "firm": "Bennett & Associates LLP"},
        },
        {
            "id": "P-009",
            "entity_type": "PERSON",
            "name": "Liam O'Connor",
            "description": "Night shift supervisor at Warehouse Dock 9, Metro Harbor.",
            "status": "ACTIVE",
            "attributes": {"dob": "1992-06-15", "badge_id": "DOCK-4401"},
        },
        {
            "id": "P-010",
            "entity_type": "PERSON",
            "name": "Amira Patel",
            "description": "Licensed customs clearance broker handling air cargo manifests at Gateway Airport.",
            "status": "ACTIVE",
            "attributes": {"dob": "1987-03-29", "customs_broker_id": "CB-9941"},
        },
        {
            "id": "P-011",
            "entity_type": "PERSON",
            "name": "David Vance",
            "description": "EDGE CASE: Unrelated software engineer residing in Boston. Shares name with P-002 but distinct national identifier and no case connection.",
            "status": "ACTIVE",
            "attributes": {"dob": "1995-10-12", "nationality": "US", "occupation": "Software Engineer", "verified_unrelated": True},
        },
        {
            "id": "P-012",
            "entity_type": "PERSON",
            "name": "Gabriel Silva",
            "description": "Telecommunications hardware vendor; identified supplier of burner SIMs and encrypted devices.",
            "status": "ACTIVE",
            "attributes": {"dob": "1991-01-25", "alias": "Gabe Hardware"},
        },
        {
            "id": "P-013",
            "entity_type": "PERSON",
            "name": "Nadia Ivanova",
            "description": "Offshore trust manager operating from Zurich Vaults Office.",
            "status": "ACTIVE",
            "attributes": {"dob": "1983-04-02", "nationality": "CH", "jurisdiction": "Switzerland"},
        },

        # ORGANIZATIONS (3)
        {
            "id": "ORG-001",
            "entity_type": "ORGANIZATION",
            "name": "Apex Holdings Ltd",
            "description": "Holding corporation registered in Delaware with offshore banking conduits in Switzerland.",
            "status": "ACTIVE",
            "attributes": {"reg_number": "DE-994120", "incorporation_date": "2021-06-15", "type": "Holding Company"},
        },
        {
            "id": "ORG-002",
            "entity_type": "ORGANIZATION",
            "name": "Meridian Logistics LLC",
            "description": "Freight forwarding and freight consolidation company operating out of Metro Harbor.",
            "status": "ACTIVE",
            "attributes": {"reg_number": "NY-448211", "dot_number": "DOT-3891002", "fleet_size": 18},
        },
        {
            "id": "ORG-003",
            "entity_type": "ORGANIZATION",
            "name": "Vanguard Trade Corp",
            "description": "Import-export firm utilized for customs invoicing and secondary routing.",
            "status": "ACTIVE",
            "attributes": {"reg_number": "NJ-102944", "vat_number": "US-8839211"},
        },

        # PHONES (4)
        {
            "id": "PH-001",
            "entity_type": "PHONE",
            "name": "+1-555-0192",
            "description": "Marcus Vance primary smartphone line (Carrier: Horizon Telecom).",
            "status": "ACTIVE",
            "attributes": {"carrier": "Horizon Telecom", "imei": "358921098234101", "primary_user": "P-001"},
        },
        {
            "id": "PH-002",
            "entity_type": "PHONE",
            "name": "+1-555-0199",
            "description": "Prepaid secondary burner phone used by Marcus Vance (Carrier: MetroPrepaid).",
            "status": "ACTIVE",
            "attributes": {"carrier": "MetroPrepaid", "imei": "864192049182390", "activation_date": "2026-01-08"},
        },
        {
            "id": "PH-003",
            "entity_type": "PHONE",
            "name": "+1-555-0841",
            "description": "Julian Thorne primary mobile device (Carrier: GlobalNet).",
            "status": "ACTIVE",
            "attributes": {"carrier": "GlobalNet", "imei": "359012948192831", "primary_user": "P-004"},
        },
        {
            "id": "PH-004",
            "entity_type": "PHONE",
            "name": "+1-555-0377",
            "description": "Elena Rostova secured encrypted line (Carrier: AlpineSecure).",
            "status": "ACTIVE",
            "attributes": {"carrier": "AlpineSecure", "encrypted": True, "primary_user": "P-003"},
        },

        # ACCOUNTS (4)
        {
            "id": "A-001",
            "entity_type": "ACCOUNT",
            "name": "CHASE-CORP-9482",
            "description": "Domestic corporate operating account at Chase Bank. Jointly associated with Marcus Vance (P-001) and Julian Thorne (P-004).",
            "status": "ACTIVE",
            "attributes": {"bank": "JPMorgan Chase", "routing": "021000021", "account_type": "Commercial Checking"},
        },
        {
            "id": "A-002",
            "entity_type": "ACCOUNT",
            "name": "HSBC-INTL-1049",
            "description": "International multi-currency account at HSBC Hong Kong registered to Apex Holdings Ltd.",
            "status": "ACTIVE",
            "attributes": {"bank": "HSBC Hong Kong", "swift": "HSBCHKHHXXX", "currency": "USD/EUR"},
        },
        {
            "id": "A-003",
            "entity_type": "ACCOUNT",
            "name": "BARCLAYS-ESC-7721",
            "description": "Escrow and structured investment account at Barclays London managed by Elena Rostova.",
            "status": "ACTIVE",
            "attributes": {"bank": "Barclays Bank UK", "iban": "GB29BARC20000077219901", "currency": "GBP/USD"},
        },
        {
            "id": "A-004",
            "entity_type": "ACCOUNT",
            "name": "SWIFT-MERIDIAN-3301",
            "description": "Operating and payroll disbursement account at Signature Trust for Meridian Logistics LLC.",
            "status": "ACTIVE",
            "attributes": {"bank": "Signature Trust NY", "routing": "026004128", "account_type": "Commercial"},
        },

        # VEHICLES (3)
        {
            "id": "V-001",
            "entity_type": "VEHICLE",
            "name": "Black Toyota Land Cruiser (Lic: 7XYZ-892)",
            "description": "2024 Black SUV registered to Meridian Logistics LLC; observed at Dock 9 meetings.",
            "status": "ACTIVE",
            "attributes": {"vin": "JTEBU5JR8K5092144", "state": "NY", "color": "Midnight Black"},
        },
        {
            "id": "V-002",
            "entity_type": "VEHICLE",
            "name": "Silver Mercedes S-Class (Lic: 4ABC-110)",
            "description": "2023 Silver sedan leased by Julian Thorne via Apex Holdings executive perks.",
            "status": "ACTIVE",
            "attributes": {"vin": "WDD2230631A992140", "state": "NJ", "color": "Iridium Silver"},
        },
        {
            "id": "V-003",
            "entity_type": "VEHICLE",
            "name": "White Ford Transit Cargo Van (Lic: 9VAN-443)",
            "description": "2022 Commercial cargo van registered to Vanguard Trade Corp.",
            "status": "ACTIVE",
            "attributes": {"vin": "1FTBR1Y84NKA10293", "state": "NY", "color": "Oxford White"},
        },

        # LOCATIONS (5)
        {
            "id": "L-001",
            "entity_type": "LOCATION",
            "name": "Warehouse Dock 9, Metro Harbor",
            "description": "Secure industrial freight facility and primary physical meeting location for Operation Meridian.",
            "status": "ACTIVE",
            "attributes": {"address": "900 Harbor Boulevard, Dock 9", "city": "Metro City", "geo": {"lat": 40.7128, "lng": -74.0060}},
        },
        {
            "id": "L-002",
            "entity_type": "LOCATION",
            "name": "Apex Financial Tower, Suite 4200",
            "description": "Corporate headquarters of Apex Holdings Ltd in the financial district.",
            "status": "ACTIVE",
            "attributes": {"address": "100 Wall Street, Floor 42", "city": "New York", "geo": {"lat": 40.7061, "lng": -74.0088}},
        },
        {
            "id": "L-003",
            "entity_type": "LOCATION",
            "name": "The Grand Oak Club Lounge",
            "description": "Exclusive private members club where Marcus Vance and Julian Thorne held off-record meetings.",
            "status": "ACTIVE",
            "attributes": {"address": "45 Park Avenue", "city": "New York", "geo": {"lat": 40.7484, "lng": -73.9857}},
        },
        {
            "id": "L-004",
            "entity_type": "LOCATION",
            "name": "Air Cargo Terminal 4, Gateway Airport",
            "description": "International air freight cargo handling zone where Vanguard Trade consignments arrived.",
            "status": "ACTIVE",
            "attributes": {"address": "Cargo Bay 4B, Gateway Airport", "city": "Queens", "geo": {"lat": 40.6413, "lng": -73.7781}},
        },
        {
            "id": "L-005",
            "entity_type": "LOCATION",
            "name": "Zurich Vaults Office, Canton Central",
            "description": "Secure Swiss repository holding corporate registries and crypto recovery keys for Apex Holdings.",
            "status": "ACTIVE",
            "attributes": {"address": "Bahnhofstrasse 88", "city": "Zurich", "country": "Switzerland"},
        },

        # DEVICES (3)
        {
            "id": "DEV-001",
            "entity_type": "DEVICE",
            "name": "Encrypted Laptop ThinkPad X1 (MAC: 48:2C:6A:11:82:90)",
            "description": "Hardened laptop recovered from Warehouse Dock 9 containing encrypted spreadsheets and ledger backups.",
            "status": "EVIDENCE_HOLD",
            "attributes": {"serial": "PF-294021K", "os": "Custom Linux Debian", "encryption": "LUKS-256"},
        },
        {
            "id": "DEV-002",
            "entity_type": "DEVICE",
            "name": "Hardware Crypto Wallet Ledger-09",
            "description": "Hardware security module containing multi-sig keys associated with offshore account A-002 routing.",
            "status": "ACTIVE",
            "attributes": {"device_model": "Ledger Nano X", "firmware": "2.2.4"},
        },
        {
            "id": "DEV-003",
            "entity_type": "DEVICE",
            "name": "Surveillance DVR Server L-001 (IP: 192.168.10.50)",
            "description": "Hikvision 32-channel network video recorder installed at Warehouse Dock 9 facility.",
            "status": "ACTIVE",
            "attributes": {"storage_tb": 16, "camera_count": 24, "retention_days": 90},
        },

        # CASE ENTITIES (2)
        {
            "id": "CASE-ENT-001",
            "entity_type": "CASE",
            "name": "CASE-001: Operation Meridian",
            "description": "Graph node representing Case NH-2026-001.",
            "status": "ACTIVE",
            "attributes": {"case_number": "NH-2026-001", "classification": "HIGH_PRIORITY"},
        },
        {
            "id": "CASE-ENT-002",
            "entity_type": "CASE",
            "name": "CASE-002: Meridian Financial Link",
            "description": "Graph node representing Case NH-2026-002.",
            "status": "REVIEW",
            "attributes": {"case_number": "NH-2026-002", "classification": "MEDIUM_PRIORITY"},
        },
    ]

    # --- 3. CASE ENTITY ASSOCIATIONS ---
    case_entities = [
        # CASE-001 (Operation Meridian)
        {"case_id": "CASE-001", "entity_id": "P-001", "role": "PRIMARY_TARGET"},
        {"case_id": "CASE-001", "entity_id": "P-002", "role": "OPERATIONS_COORDINATOR"},
        {"case_id": "CASE-001", "entity_id": "P-003", "role": "FINANCIAL_BROKER"},
        {"case_id": "CASE-001", "entity_id": "P-004", "role": "KEY_FACILITATOR"}, # Cross-case connection
        {"case_id": "CASE-001", "entity_id": "P-006", "role": "TRANSPORT_MANAGER"},
        {"case_id": "CASE-001", "entity_id": "P-007", "role": "ACCOUNTANT"},
        {"case_id": "CASE-001", "entity_id": "P-008", "role": "LEGAL_COUNSEL"},
        {"case_id": "CASE-001", "entity_id": "P-009", "role": "DOCK_SUPERVISOR"},
        {"case_id": "CASE-001", "entity_id": "P-010", "role": "CUSTOMS_AGENT"},
        {"case_id": "CASE-001", "entity_id": "ORG-001", "role": "PARENT_HOLDING"},
        {"case_id": "CASE-001", "entity_id": "ORG-002", "role": "LOGISTICS_HUB"},
        {"case_id": "CASE-001", "entity_id": "ORG-003", "role": "TRADE_INTERMEDIARY"},
        {"case_id": "CASE-001", "entity_id": "PH-001", "role": "PRIMARY_COMM"},
        {"case_id": "CASE-001", "entity_id": "PH-002", "role": "BURNER_COMM"},
        {"case_id": "CASE-001", "entity_id": "PH-003", "role": "FACILITATOR_COMM"},
        {"case_id": "CASE-001", "entity_id": "A-001", "role": "PRIMARY_OPERATING_ACCOUNT"},
        {"case_id": "CASE-001", "entity_id": "A-004", "role": "PAYROLL_ACCOUNT"},
        {"case_id": "CASE-001", "entity_id": "V-001", "role": "SURVEILLANCE_VEHICLE"},
        {"case_id": "CASE-001", "entity_id": "V-002", "role": "EXECUTIVE_VEHICLE"},
        {"case_id": "CASE-001", "entity_id": "V-003", "role": "CARGO_VEHICLE"},
        {"case_id": "CASE-001", "entity_id": "L-001", "role": "PRIMARY_FACILITY"},
        {"case_id": "CASE-001", "entity_id": "L-002", "role": "CORPORATE_OFFICE"},
        {"case_id": "CASE-001", "entity_id": "L-003", "role": "MEETING_VENUE"},
        {"case_id": "CASE-001", "entity_id": "DEV-001", "role": "SEIZED_DEVICE"},
        {"case_id": "CASE-001", "entity_id": "DEV-003", "role": "CCTV_SYSTEM"},

        # CASE-002 (Meridian Financial Link)
        {"case_id": "CASE-002", "entity_id": "P-004", "role": "CROSS_CASE_CONDUIT"}, # PATTERN 2 CROSS-CASE
        {"case_id": "CASE-002", "entity_id": "P-003", "role": "OFFSHORE_TRUSTEE"},
        {"case_id": "CASE-002", "entity_id": "P-005", "role": "INTERNAL_AUDITOR"},
        {"case_id": "CASE-002", "entity_id": "P-013", "role": "SWISS_ADMINISTRATOR"},
        {"case_id": "CASE-002", "entity_id": "ORG-001", "role": "PRIMARY_INVESTIGATION_TARGET"},
        {"case_id": "CASE-002", "entity_id": "A-001", "role": "ORIGINATING_DOMESTIC_ACCOUNT"},
        {"case_id": "CASE-002", "entity_id": "A-002", "role": "OFFSHORE_CONDUIT_ACCOUNT"},
        {"case_id": "CASE-002", "entity_id": "A-003", "role": "ESCROW_ROUTING_ACCOUNT"},
        {"case_id": "CASE-002", "entity_id": "L-002", "role": "HEADQUARTERS"},
        {"case_id": "CASE-002", "entity_id": "L-005", "role": "OFFSHORE_VAULT"},
        {"case_id": "CASE-002", "entity_id": "DEV-002", "role": "CRYPTO_SECURITY_MODULE"},
    ]

    # --- 4. SOURCES (25 records) ---
    sources = [
        {
            "id": "SRC-001",
            "source_type": "FIR",
            "reference_code": "FIR-2026-0091",
            "title": "First Information Report - Metro Harbor Port Security",
            "description": "Initial port authority report regarding irregular late-night container loading at Dock 9.",
            "source_date": datetime(2026, 1, 6, 10, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-002",
            "source_type": "CDR",
            "reference_code": "CDR-HORIZON-2026-01",
            "title": "Call Detail Records - Horizon Telecom PH-001",
            "description": "Subpoenaed call detail records for Marcus Vance mobile +1-555-0192 covering Jan-Feb 2026.",
            "source_date": datetime(2026, 1, 12, 15, 30, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-003",
            "source_type": "CDR",
            "reference_code": "CDR-GLOBALNET-2026-01",
            "title": "Call Detail Records - GlobalNet PH-003",
            "description": "Subpoenaed call detail records for Julian Thorne mobile +1-555-0841.",
            "source_date": datetime(2026, 1, 14, 11, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-004",
            "source_type": "SURVEILLANCE",
            "reference_code": "SURV-2026-0115",
            "title": "Physical Surveillance Log - Warehouse Dock 9",
            "description": "Visual surveillance team observation of meeting between Marcus Vance and Julian Thorne at Dock 9 on Jan 15.",
            "source_date": datetime(2026, 1, 16, 8, 30, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-005",
            "source_type": "FINANCIAL_RECORD",
            "reference_code": "FIN-CHASE-2026-01",
            "title": "Chase Bank Account Statement A-001 (Jan 2026)",
            "description": "Certified bank statement showing $250,000 wire transaction authorized by Julian Thorne.",
            "source_date": datetime(2026, 1, 22, 14, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-006",
            "source_type": "VEHICLE_RECORD",
            "reference_code": "DMV-NY-2026-V01",
            "title": "NY DMV Vehicle Registration Record V-001",
            "description": "Registration for 2024 Black Toyota Land Cruiser (7XYZ-892) under Meridian Logistics LLC.",
            "source_date": datetime(2026, 1, 7, 9, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-007",
            "source_type": "VEHICLE_RECORD",
            "reference_code": "DMV-NJ-2026-V02",
            "title": "NJ DMV Vehicle Lease Record V-002",
            "description": "Executive lease filing for Mercedes S-Class (4ABC-110) registered to Julian Thorne.",
            "source_date": datetime(2026, 1, 9, 13, 15, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-008",
            "source_type": "PUBLIC_RECORD",
            "reference_code": "CORP-DE-2021-ORG01",
            "title": "Delaware Corporate Registry - Apex Holdings Ltd",
            "description": "Certificate of incorporation and listed directors for Apex Holdings Ltd.",
            "source_date": datetime(2026, 1, 8, 16, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-009",
            "source_type": "PUBLIC_RECORD",
            "reference_code": "CORP-NY-2022-ORG02",
            "title": "NY Dept of State Filing - Meridian Logistics LLC",
            "description": "Articles of organization listing David Vance and Marcus Vance as managing members.",
            "source_date": datetime(2026, 1, 8, 16, 30, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-010",
            "source_type": "INTERVIEW",
            "reference_code": "INT-2026-003",
            "title": "Witness Interview - Liam O'Connor (Dock Supervisor)",
            "description": "Sworn interview regarding after-hours access at Warehouse Dock 9 and offloading logs.",
            "source_date": datetime(2026, 1, 28, 10, 30, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-011",
            "source_type": "FINANCIAL_RECORD",
            "reference_code": "FIN-CHASE-SIG-A001",
            "title": "Signature Card & Mandate Agreement - Account A-001",
            "description": "Bank signature cards establishing Marcus Vance as primary signatory and Julian Thorne as authorized transactor.",
            "source_date": datetime(2026, 2, 4, 11, 45, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-012",
            "source_type": "FINANCIAL_RECORD",
            "reference_code": "FIN-HSBC-2026-02",
            "title": "HSBC Wire Audit - Account A-002",
            "description": "International SWIFT transfer confirmations between Chase A-001 and HSBC HK A-002.",
            "source_date": datetime(2026, 2, 18, 14, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-002",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-013",
            "source_type": "SURVEILLANCE",
            "reference_code": "SURV-2026-0210",
            "title": "CCTV Footage Extraction - Apex Financial Tower",
            "description": "Building security DVR log showing Elena Rostova and Julian Thorne meeting on 42nd floor.",
            "source_date": datetime(2026, 2, 12, 17, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-002",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-014",
            "source_type": "CASE_REPORT",
            "reference_code": "REP-2026-FEBINV",
            "title": "Interim Investigative Report - Expansion Phase",
            "description": "Intelligence synthesis establishing network expansion from logistics into cross-border holding accounts.",
            "source_date": datetime(2026, 2, 25, 18, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-015",
            "source_type": "INTERVIEW",
            "reference_code": "INT-2026-007",
            "title": "Confidential Interview - Sophia Chen (Compliance)",
            "description": "Statement from Sophia Chen disclosing offshore escrow conduits and unlogged asset flows.",
            "source_date": datetime(2026, 3, 3, 13, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-002",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-016",
            "source_type": "FINANCIAL_RECORD",
            "reference_code": "FIN-BARCLAYS-2026-03",
            "title": "Barclays Escrow Ledger - Account A-003",
            "description": "Ledger printout detailing $1.2M escrow distribution from Barclays UK to Swiss trust account.",
            "source_date": datetime(2026, 3, 10, 15, 30, 0, tzinfo=timezone.utc),
            "case_id": "CASE-002",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-017",
            "source_type": "CASE_REPORT",
            "reference_code": "REP-2026-CROSSCASE",
            "title": "Cross-Case Nexus Briefing - CASE-001 to CASE-002",
            "description": "Formal referral linking Julian Thorne (P-004) from Operation Meridian to Meridian Financial Link.",
            "source_date": datetime(2026, 3, 15, 9, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-002",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-018",
            "source_type": "CDR",
            "reference_code": "CDR-PREPAID-2026-0199",
            "title": "Burner SIM Activation Log PH-002",
            "description": "Telecom retail log linking prepaid burner SIM +1-555-0199 to Gabriel Silva storefront.",
            "source_date": datetime(2026, 1, 18, 16, 45, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "AMBIGUOUS",
        },
        {
            "id": "SRC-019",
            "source_type": "SYNTHETIC_RECORD",
            "reference_code": "TIP-ANON-2026-881",
            "title": "Anonymous Hotline Tip (Contradictory)",
            "description": "EDGE CASE: Unverified caller claimed Marcus Vance was in Dubai on Jan 15 (contradicted by verified CCTV & GPS at Dock 9).",
            "source_date": datetime(2026, 1, 19, 21, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "CONTRADICTED",
        },
        {
            "id": "SRC-020",
            "source_type": "PUBLIC_RECORD",
            "reference_code": "CORP-NJ-2023-ORG03",
            "title": "NJ Commercial Registry - Vanguard Trade Corp",
            "description": "State registration for Vanguard Trade Corp showing Tariq Mansoor as registered agent.",
            "source_date": datetime(2026, 1, 11, 10, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-021",
            "source_type": "PUBLIC_RECORD",
            "reference_code": "HR-RECORD-2025-VRAMOS",
            "title": "Meridian Logistics Historic Payroll Record (Ended)",
            "description": "EDGE CASE: HR documentation verifying Viktor Ramos employment ended on Nov 30, 2025.",
            "source_date": datetime(2025, 12, 1, 9, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-022",
            "source_type": "PUBLIC_RECORD",
            "reference_code": "HIST-CORP-2024-TARIQ",
            "title": "Historic Consulting Agreement 2024 (Old Relationship)",
            "description": "EDGE CASE: Consulting agreement between Tariq Mansoor and Vanguard Trade valid only Jan-Jun 2024.",
            "source_date": datetime(2024, 1, 5, 10, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "EXPIRED",
        },
        {
            "id": "SRC-023",
            "source_type": "SURVEILLANCE",
            "reference_code": "FORENSIC-DVR-L001",
            "title": "Digital Forensics Report - DEV-003 DVR Recovery",
            "description": "Extraction of timestamps, vehicle license plate recognition, and visitor logs from Dock 9 DVR server.",
            "source_date": datetime(2026, 2, 2, 14, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-024",
            "source_type": "FINANCIAL_RECORD",
            "reference_code": "FIN-CHASE-PAYROLL-A004",
            "title": "Signature Trust Payroll Disbursement Log A-004",
            "description": "Direct deposit records for Meridian Logistics employees and warehouse staff.",
            "source_date": datetime(2026, 1, 31, 17, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
        {
            "id": "SRC-025",
            "source_type": "SYNTHETIC_RECORD",
            "reference_code": "SYNTH-INTEL-BENCHMARK-09",
            "title": "Synthetic Investigation Benchmark Metadata Package",
            "description": "Overall synthetic dataset declaration and scenario control manifest.",
            "source_date": datetime(2026, 1, 5, 8, 0, 0, tzinfo=timezone.utc),
            "case_id": "CASE-001",
            "status": "VERIFIED",
        },
    ]

    # --- 5. EVIDENCE (25 records) ---
    evidence = [
        {
            "id": "EVD-001",
            "source_id": "SRC-001",
            "case_id": "CASE-001",
            "evidence_type": "INCIDENT_REPORT",
            "title": "Port Security Observation at Dock 9",
            "content": "On Jan 5, 2026 at 23:15, security observed unauthorized vehicle V-001 entering Warehouse Dock 9. Marcus Vance was identified presenting supervisory badge.",
            "evidence_date": datetime(2026, 1, 5, 23, 15, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-002",
            "source_id": "SRC-002",
            "case_id": "CASE-001",
            "evidence_type": "CDR_TRANSCRIPT",
            "title": "Call Intercept Record - Jan 10 (P-001 to P-004)",
            "content": "Call duration 428s between +1-555-0192 (P-001) and +1-555-0841 (P-004). Discussed scheduling on-site review at Dock 9 for Jan 15.",
            "evidence_date": datetime(2026, 1, 10, 14, 22, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-003",
            "source_id": "SRC-004",
            "case_id": "CASE-001",
            "evidence_type": "SURVEILLANCE_PHOTO",
            "title": "Dock 9 Meeting Photographic Log - Jan 15",
            "content": "Surveillance team captured high-resolution photographs of Marcus Vance (P-001) and Julian Thorne (P-004) entering Warehouse Dock 9 at 19:45.",
            "evidence_date": datetime(2026, 1, 15, 19, 45, 0, tzinfo=timezone.utc),
            "verification_status": "OBSERVED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-004",
            "source_id": "SRC-005",
            "case_id": "CASE-001",
            "evidence_type": "BANK_WIRE_CONFIRMATION",
            "title": "Chase Wire Transfer $250k Confirmation - Jan 20",
            "content": "Outbound Fedwire of $250,000.00 from Account A-001 to offshore escrow account A-003. Transaction initiated and signed digitally by Julian Thorne.",
            "evidence_date": datetime(2026, 1, 20, 11, 30, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-005",
            "source_id": "SRC-011",
            "case_id": "CASE-001",
            "evidence_type": "BANK_MANDATE",
            "title": "Chase Signature Mandate for Account A-001",
            "content": "Official bank mandate establishing Marcus Vance as beneficial owner and Julian Thorne as authorized trading officer for Account A-001.",
            "evidence_date": datetime(2026, 2, 4, 11, 45, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-006",
            "source_id": "SRC-006",
            "case_id": "CASE-001",
            "evidence_type": "DMV_TITLE",
            "title": "Vehicle Title Record V-001",
            "content": "Certificate of title verifying Meridian Logistics LLC ownership of 2024 Black Land Cruiser (7XYZ-892).",
            "evidence_date": datetime(2026, 1, 7, 9, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-007",
            "source_id": "SRC-007",
            "case_id": "CASE-001",
            "evidence_type": "LEASE_AGREEMENT",
            "title": "Executive Vehicle Lease V-002",
            "content": "Lease documentation establishing Julian Thorne as sole named driver of Mercedes S-Class (4ABC-110).",
            "evidence_date": datetime(2026, 1, 9, 13, 15, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-008",
            "source_id": "SRC-008",
            "case_id": "CASE-001",
            "evidence_type": "CORPORATE_FILING",
            "title": "Apex Holdings Corporate Register",
            "content": "Delaware public filing showing Elena Rostova registered as resident managing agent of Apex Holdings Ltd.",
            "evidence_date": datetime(2026, 1, 8, 16, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-009",
            "source_id": "SRC-009",
            "case_id": "CASE-001",
            "evidence_type": "CORPORATE_FILING",
            "title": "Meridian Logistics Operating Agreement",
            "content": "Operating agreement showing 60% ownership by Marcus Vance and 40% by David Vance.",
            "evidence_date": datetime(2026, 1, 8, 16, 30, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-010",
            "source_id": "SRC-010",
            "case_id": "CASE-001",
            "evidence_type": "SWORN_STATEMENT",
            "title": "Liam O'Connor Witness Statement",
            "content": "Liam O'Connor confirmed unlocking Bay 3 for Marcus Vance and Julian Thorne on Jan 15, noting multiple Pelican cases loaded into V-001.",
            "evidence_date": datetime(2026, 1, 28, 10, 30, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-011",
            "source_id": "SRC-012",
            "case_id": "CASE-002",
            "evidence_type": "SWIFT_LOG",
            "title": "SWIFT MT103 Offshore Transmission",
            "content": "SWIFT confirmation of $500,000 credit from Chase A-001 into HSBC Hong Kong account A-002 on Feb 18, 2026.",
            "evidence_date": datetime(2026, 2, 18, 14, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-012",
            "source_id": "SRC-013",
            "case_id": "CASE-002",
            "evidence_type": "CCTV_STILL",
            "title": "Apex Financial Tower Meeting Footage - Feb 12",
            "content": "CCTV timestamps verify Julian Thorne and Elena Rostova entering Suite 4200 together at 14:15 on Feb 12, 2026.",
            "evidence_date": datetime(2026, 2, 12, 14, 15, 0, tzinfo=timezone.utc),
            "verification_status": "OBSERVED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-013",
            "source_id": "SRC-015",
            "case_id": "CASE-002",
            "evidence_type": "WHISTLEBLOWER_MEMO",
            "title": "Sophia Chen Internal Compliance Memo",
            "content": "Sophia Chen documented three unverified wire exemptions flagged for Julian Thorne totaling $1.8M over Q1 2026.",
            "evidence_date": datetime(2026, 3, 3, 13, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-014",
            "source_id": "SRC-016",
            "case_id": "CASE-002",
            "evidence_type": "BANK_LEDGER",
            "title": "Barclays Escrow Account Statement A-003",
            "content": "Monthly audit verifying escrow balance disbursements from A-003 to Zurich Vaults trust entity managed by Nadia Ivanova.",
            "evidence_date": datetime(2026, 3, 10, 15, 30, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-015",
            "source_id": "SRC-017",
            "case_id": "CASE-002",
            "evidence_type": "INTELLIGENCE_MEMO",
            "title": "Cross-Case Nexus Finding on Julian Thorne",
            "content": "Formal finding linking Julian Thorne (P-004) from Operation Meridian (CASE-001) to the offshore financial architecture in CASE-002.",
            "evidence_date": datetime(2026, 3, 15, 9, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-016",
            "source_id": "SRC-018",
            "case_id": "CASE-001",
            "evidence_type": "TELECOM_AUDIT",
            "title": "Burner Phone PH-002 Telecom Association",
            "content": "Burner phone +1-555-0199 was purchased with cash from Gabriel Silva kiosk; cell tower triangulation places it co-located with P-001 primary phone.",
            "evidence_date": datetime(2026, 1, 18, 16, 45, 0, tzinfo=timezone.utc),
            "verification_status": "AMBIGUOUS",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-017",
            "source_id": "SRC-019",
            "case_id": "CASE-001",
            "evidence_type": "TIP_LOG",
            "title": "Contradictory Anonymous Tip on Marcus Vance Location",
            "content": "EDGE CASE: Anonymous tip asserted Marcus Vance was in Dubai on Jan 15. Disproven by physical surveillance EVD-003 at Dock 9.",
            "evidence_date": datetime(2026, 1, 19, 21, 0, 0, tzinfo=timezone.utc),
            "verification_status": "CONTRADICTED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-018",
            "source_id": "SRC-021",
            "case_id": "CASE-001",
            "evidence_type": "TERMINATION_LETTER",
            "title": "Viktor Ramos Employment Termination Letter",
            "content": "EDGE CASE: Official letter confirming Viktor Ramos was terminated from Meridian Logistics on Nov 30, 2025.",
            "evidence_date": datetime(2025, 11, 30, 17, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-019",
            "source_id": "SRC-022",
            "case_id": "CASE-001",
            "evidence_type": "CONSULTING_CONTRACT",
            "title": "2024 Historic Consulting Contract Tariq Mansoor",
            "content": "EDGE CASE: 6-month consulting contract between Tariq Mansoor and Vanguard Trade expiring June 30, 2024.",
            "evidence_date": datetime(2024, 1, 5, 10, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-020",
            "source_id": "SRC-023",
            "case_id": "CASE-001",
            "evidence_type": "FORENSIC_EXTRACTION",
            "title": "DEV-003 CCTV Server Video Hash Log",
            "content": "Forensic copy of 24-hour video logs from Dock 9 DVR matching vehicle movements of V-001, V-002, and V-003.",
            "evidence_date": datetime(2026, 2, 2, 14, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-021",
            "source_id": "SRC-002",
            "case_id": "CASE-001",
            "evidence_type": "CDR_LOG",
            "title": "Call Logs Marcus Vance to David Vance",
            "content": "Frequent 5-minute morning calls between Marcus Vance (PH-001) and brother David Vance regarding daily warehouse consignments.",
            "evidence_date": datetime(2026, 1, 14, 8, 30, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-022",
            "source_id": "SRC-010",
            "case_id": "CASE-001",
            "evidence_type": "SEIZURE_RECEIPT",
            "title": "Property Receipt for Seized Laptop DEV-001",
            "content": "Chain-of-custody log for Lenovo ThinkPad X1 seized from supervisory desk at Warehouse Dock 9.",
            "evidence_date": datetime(2026, 1, 29, 11, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-023",
            "source_id": "SRC-020",
            "case_id": "CASE-001",
            "evidence_type": "CUSTOMS_MANIFEST",
            "title": "Air Cargo Freight Manifest at Gateway Airport",
            "content": "Customs clearance manifest for 6 air freight pallets processed by Amira Patel (P-010) on behalf of Vanguard Trade Corp.",
            "evidence_date": datetime(2026, 1, 21, 15, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-024",
            "source_id": "SRC-016",
            "case_id": "CASE-002",
            "evidence_type": "CRYPTO_AUDIT",
            "title": "Hardware Wallet DEV-002 Extraction Report",
            "content": "Digital forensics analysis of Ledger Nano X hardware wallet linked to multi-sig authorization of account A-002.",
            "evidence_date": datetime(2026, 3, 11, 16, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
        {
            "id": "EVD-025",
            "source_id": "SRC-025",
            "case_id": "CASE-001",
            "evidence_type": "BENCHMARK_CERT",
            "title": "Synthetic Investigation Evidence Certification",
            "content": "Standardized benchmark artifact proving complete provenance chain from entity to evidence for Network Hunter PS09.",
            "evidence_date": datetime(2026, 1, 5, 8, 0, 0, tzinfo=timezone.utc),
            "verification_status": "VERIFIED",
            "extra_metadata": SYNTHETIC_METADATA,
        },
    ]

    # --- 6. RELATIONSHIPS (38 records with full provenance) ---
    relationships = [
        # Pattern 1: Shared Account A-001 (P-001 & P-004)
        {
            "id": "REL-001",
            "from_entity_id": "P-001",
            "to_entity_id": "A-001",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Marcus Vance is registered beneficial owner of Chase Account A-001.",
            "start_time": datetime(2026, 2, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-011",
        },
        {
            "id": "REL-002",
            "from_entity_id": "P-004",
            "to_entity_id": "A-001",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Julian Thorne is authorized trading officer and transactor on Chase Account A-001.",
            "start_time": datetime(2026, 2, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-011",
        },

        # Pattern 2 & 4: Expansion from P-001 -> P-004 -> CASE-002
        {
            "id": "REL-003",
            "from_entity_id": "P-001",
            "to_entity_id": "P-004",
            "relationship_type": "CONNECTED_TO",
            "description": "Direct communication and operational coordination between Marcus Vance and Julian Thorne.",
            "start_time": datetime(2026, 1, 10, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 0.95,
            "case_id": "CASE-001",
            "source_id": "SRC-002",
        },
        {
            "id": "REL-004",
            "from_entity_id": "P-004",
            "to_entity_id": "ORG-001",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Julian Thorne acts as financial intermediary for Apex Holdings Ltd.",
            "start_time": datetime(2026, 3, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 0.92,
            "case_id": "CASE-002",
            "source_id": "SRC-017",
        },
        {
            "id": "REL-005",
            "from_entity_id": "P-004",
            "to_entity_id": "CASE-ENT-001",
            "relationship_type": "INVOLVED_IN",
            "description": "Julian Thorne implicated as primary logistics facilitator in Operation Meridian.",
            "start_time": datetime(2026, 1, 15, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-004",
        },
        {
            "id": "REL-006",
            "from_entity_id": "P-004",
            "to_entity_id": "CASE-ENT-002",
            "relationship_type": "INVOLVED_IN",
            "description": "Julian Thorne identified as cross-case financial bridge in Meridian Financial Link.",
            "start_time": datetime(2026, 3, 15, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-017",
        },

        # P-001 Phones & Ownership (EDGE CASE: multiple phones)
        {
            "id": "REL-007",
            "from_entity_id": "P-001",
            "to_entity_id": "PH-001",
            "relationship_type": "OWNED",
            "description": "Marcus Vance primary registered smartphone +1-555-0192.",
            "start_time": datetime(2025, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-002",
        },
        {
            "id": "REL-008",
            "from_entity_id": "P-001",
            "to_entity_id": "PH-002",
            "relationship_type": "USED",
            "description": "EDGE CASE: Marcus Vance observed using secondary prepaid burner line +1-555-0199.",
            "start_time": datetime(2026, 1, 8, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 0.85,
            "case_id": "CASE-001",
            "source_id": "SRC-018",
        },
        {
            "id": "REL-009",
            "from_entity_id": "P-004",
            "to_entity_id": "PH-003",
            "relationship_type": "OWNED",
            "description": "Julian Thorne registered mobile line +1-555-0841.",
            "start_time": datetime(2025, 6, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-003",
        },
        {
            "id": "REL-010",
            "from_entity_id": "P-003",
            "to_entity_id": "PH-004",
            "relationship_type": "OWNED",
            "description": "Elena Rostova secured phone line +1-555-0377.",
            "start_time": datetime(2025, 3, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-013",
        },

        # Calls between phones
        {
            "id": "REL-011",
            "from_entity_id": "PH-001",
            "to_entity_id": "PH-003",
            "relationship_type": "CALLED",
            "description": "Phone call on Jan 10 prior to Dock 9 meeting.",
            "start_time": datetime(2026, 1, 10, 14, 22, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-002",
        },

        # Corporate relationships & leadership
        {
            "id": "REL-012",
            "from_entity_id": "P-001",
            "to_entity_id": "ORG-002",
            "relationship_type": "WORKS_AT",
            "description": "Marcus Vance is Managing Partner of Meridian Logistics LLC.",
            "start_time": datetime(2022, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-009",
        },
        {
            "id": "REL-013",
            "from_entity_id": "P-002",
            "to_entity_id": "ORG-002",
            "relationship_type": "WORKS_AT",
            "description": "David Vance is Operations Manager of Meridian Logistics LLC.",
            "start_time": datetime(2022, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-009",
        },
        {
            "id": "REL-014",
            "from_entity_id": "P-001",
            "to_entity_id": "P-002",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Marcus Vance and David Vance are brothers and business partners.",
            "start_time": datetime(2000, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-009",
        },
        {
            "id": "REL-015",
            "from_entity_id": "P-003",
            "to_entity_id": "ORG-001",
            "relationship_type": "WORKS_AT",
            "description": "Elena Rostova is Managing Agent and Trustee for Apex Holdings Ltd.",
            "start_time": datetime(2021, 6, 15, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-008",
        },
        {
            "id": "REL-016",
            "from_entity_id": "P-005",
            "to_entity_id": "ORG-001",
            "relationship_type": "WORKS_AT",
            "description": "Sophia Chen is Senior Compliance Officer at Apex Holdings Ltd.",
            "start_time": datetime(2023, 4, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-015",
        },

        # EDGE CASE 3: Relationship with an END DATE (Viktor Ramos terminated)
        {
            "id": "REL-017",
            "from_entity_id": "P-006",
            "to_entity_id": "ORG-002",
            "relationship_type": "WORKS_AT",
            "description": "EDGE CASE: Viktor Ramos was employed as transport manager until Nov 30, 2025.",
            "start_time": datetime(2023, 2, 1, tzinfo=timezone.utc),
            "end_time": datetime(2025, 11, 30, tzinfo=timezone.utc),
            "status": "TERMINATED",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-021",
        },

        # EDGE CASE 7: Old relationship outside 2026 timeline
        {
            "id": "REL-018",
            "from_entity_id": "P-007",
            "to_entity_id": "ORG-003",
            "relationship_type": "WORKS_AT",
            "description": "EDGE CASE: Tariq Mansoor 2024 consulting contract with Vanguard Trade Corp.",
            "start_time": datetime(2024, 1, 1, tzinfo=timezone.utc),
            "end_time": datetime(2024, 6, 30, tzinfo=timezone.utc),
            "status": "EXPIRED",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-022",
        },

        # Corporate Accounts & Wire Transfers
        {
            "id": "REL-019",
            "from_entity_id": "ORG-002",
            "to_entity_id": "A-004",
            "relationship_type": "OWNED",
            "description": "Signature Trust Account A-004 owned by Meridian Logistics LLC.",
            "start_time": datetime(2022, 5, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-024",
        },
        {
            "id": "REL-020",
            "from_entity_id": "ORG-001",
            "to_entity_id": "A-002",
            "relationship_type": "OWNED",
            "description": "HSBC Hong Kong Account A-002 owned by Apex Holdings Ltd.",
            "start_time": datetime(2021, 8, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-012",
        },
        {
            "id": "REL-021",
            "from_entity_id": "P-003",
            "to_entity_id": "A-003",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Elena Rostova manages Barclays Escrow Account A-003.",
            "start_time": datetime(2024, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-016",
        },
        {
            "id": "REL-022",
            "from_entity_id": "A-001",
            "to_entity_id": "A-003",
            "relationship_type": "TRANSFERRED_TO",
            "description": "$250,000 transfer on Jan 20 from Chase A-001 to Barclays Escrow A-003.",
            "start_time": datetime(2026, 1, 20, 11, 30, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-005",
        },
        {
            "id": "REL-023",
            "from_entity_id": "A-001",
            "to_entity_id": "A-002",
            "relationship_type": "TRANSFERRED_TO",
            "description": "$500,000 transfer on Feb 18 from Chase A-001 to HSBC HK A-002.",
            "start_time": datetime(2026, 2, 18, 14, 0, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-012",
        },

        # Vehicles & Ownership
        {
            "id": "REL-024",
            "from_entity_id": "ORG-002",
            "to_entity_id": "V-001",
            "relationship_type": "OWNED",
            "description": "Toyota Land Cruiser V-001 owned by Meridian Logistics LLC.",
            "start_time": datetime(2024, 2, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-006",
        },
        {
            "id": "REL-025",
            "from_entity_id": "P-004",
            "to_entity_id": "V-002",
            "relationship_type": "USED",
            "description": "Mercedes S-Class V-002 leased and operated by Julian Thorne.",
            "start_time": datetime(2023, 9, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-007",
        },
        {
            "id": "REL-026",
            "from_entity_id": "ORG-003",
            "to_entity_id": "V-003",
            "relationship_type": "OWNED",
            "description": "Ford Transit Van V-003 owned by Vanguard Trade Corp.",
            "start_time": datetime(2023, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-020",
        },

        # Locations & Visits
        {
            "id": "REL-027",
            "from_entity_id": "P-001",
            "to_entity_id": "L-001",
            "relationship_type": "VISITED",
            "description": "Marcus Vance frequent presence at Warehouse Dock 9.",
            "start_time": datetime(2026, 1, 5, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-001",
        },
        {
            "id": "REL-028",
            "from_entity_id": "P-004",
            "to_entity_id": "L-001",
            "relationship_type": "VISITED",
            "description": "Julian Thorne visited Warehouse Dock 9 for coordination meeting on Jan 15.",
            "start_time": datetime(2026, 1, 15, 19, 45, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-004",
        },
        {
            "id": "REL-029",
            "from_entity_id": "P-004",
            "to_entity_id": "L-002",
            "relationship_type": "VISITED",
            "description": "Julian Thorne visited Apex Financial Tower on Feb 12.",
            "start_time": datetime(2026, 2, 12, 14, 15, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-013",
        },
        {
            "id": "REL-030",
            "from_entity_id": "P-001",
            "to_entity_id": "L-003",
            "relationship_type": "VISITED",
            "description": "Marcus Vance off-record meetings at Grand Oak Club Lounge.",
            "start_time": datetime(2026, 1, 25, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 0.90,
            "case_id": "CASE-001",
            "source_id": "SRC-004",
        },
        {
            "id": "REL-031",
            "from_entity_id": "ORG-002",
            "to_entity_id": "L-001",
            "relationship_type": "LOCATED_AT",
            "description": "Meridian Logistics main operating warehouse facility is at Dock 9.",
            "start_time": datetime(2022, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-009",
        },
        {
            "id": "REL-032",
            "from_entity_id": "ORG-001",
            "to_entity_id": "L-002",
            "relationship_type": "LOCATED_AT",
            "description": "Apex Holdings headquarters is located at Apex Financial Tower Suite 4200.",
            "start_time": datetime(2021, 6, 15, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-002",
            "source_id": "SRC-008",
        },

        # Devices
        {
            "id": "REL-033",
            "from_entity_id": "DEV-001",
            "to_entity_id": "L-001",
            "relationship_type": "LOCATED_AT",
            "description": "Encrypted Laptop DEV-001 seized from Warehouse Dock 9.",
            "start_time": datetime(2026, 1, 29, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-010",
        },
        {
            "id": "REL-034",
            "from_entity_id": "DEV-003",
            "to_entity_id": "L-001",
            "relationship_type": "LOCATED_AT",
            "description": "CCTV DVR server DEV-003 installed at Warehouse Dock 9.",
            "start_time": datetime(2024, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-023",
        },
        {
            "id": "REL-035",
            "from_entity_id": "P-003",
            "to_entity_id": "DEV-002",
            "relationship_type": "USED",
            "description": "Elena Rostova holds hardware key Ledger DEV-002 for offshore multi-sig transfers.",
            "start_time": datetime(2025, 1, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 0.95,
            "case_id": "CASE-002",
            "source_id": "SRC-016",
        },

        # EDGE CASE 5: Ambiguous identity relationship
        {
            "id": "REL-036",
            "from_entity_id": "P-012",
            "to_entity_id": "PH-002",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "EDGE CASE: Gabriel Silva suspected of provisioning burner SIM +1-555-0199 (Ambiguous confirmation).",
            "start_time": datetime(2026, 1, 8, tzinfo=timezone.utc),
            "end_time": None,
            "status": "AMBIGUOUS",
            "confidence": 0.45,
            "case_id": "CASE-001",
            "source_id": "SRC-018",
        },

        # Supporting Associates
        {
            "id": "REL-037",
            "from_entity_id": "P-009",
            "to_entity_id": "ORG-002",
            "relationship_type": "WORKS_AT",
            "description": "Liam O'Connor employed as dock supervisor by Meridian Logistics.",
            "start_time": datetime(2024, 3, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-010",
        },
        {
            "id": "REL-038",
            "from_entity_id": "P-010",
            "to_entity_id": "ORG-003",
            "relationship_type": "ASSOCIATED_WITH",
            "description": "Amira Patel provides customs clearance brokerage for Vanguard Trade Corp.",
            "start_time": datetime(2024, 6, 1, tzinfo=timezone.utc),
            "end_time": None,
            "status": "ACTIVE",
            "confidence": 1.0,
            "case_id": "CASE-001",
            "source_id": "SRC-020",
        },
    ]

    # --- 7. EVENTS (23 chronologically structured events) ---
    events = [
        # Jan 5: Initial Incident
        {
            "id": "EVT-001",
            "event_type": "SURVEILLANCE_SIGHTING",
            "timestamp": datetime(2026, 1, 5, 23, 15, 0, tzinfo=timezone.utc),
            "description": "Late-night entry of vehicle V-001 at Warehouse Dock 9 observed by port authority.",
            "location_id": "L-001",
            "case_id": "CASE-001",
            "source_id": "SRC-001",
            "participants": [
                {"entity_id": "P-001", "role": "DRIVER"},
                {"entity_id": "V-001", "role": "VEHICLE"},
                {"entity_id": "L-001", "role": "LOCATION"},
            ],
        },

        # PATTERN 3 - SEQUENCE STEP 1: Jan 10 Call
        {
            "id": "EVT-002",
            "event_type": "CALL",
            "timestamp": datetime(2026, 1, 10, 14, 22, 0, tzinfo=timezone.utc),
            "description": "Marcus Vance calls Julian Thorne to plan on-site meeting at Dock 9.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-002",
            "participants": [
                {"entity_id": "P-001", "role": "CALLER"},
                {"entity_id": "P-004", "role": "RECEIVER"},
                {"entity_id": "PH-001", "role": "CALLER_DEVICE"},
                {"entity_id": "PH-003", "role": "RECEIVER_DEVICE"},
            ],
        },

        # Jan 12: Morning Coordination Call
        {
            "id": "EVT-003",
            "event_type": "CALL",
            "timestamp": datetime(2026, 1, 12, 9, 15, 0, tzinfo=timezone.utc),
            "description": "Marcus Vance coordinates with David Vance on warehouse staffing schedules.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-002",
            "participants": [
                {"entity_id": "P-001", "role": "CALLER"},
                {"entity_id": "P-002", "role": "RECEIVER"},
            ],
        },

        # PATTERN 3 - SEQUENCE STEP 2: Jan 15 Meeting
        {
            "id": "EVT-004",
            "event_type": "MEETING",
            "timestamp": datetime(2026, 1, 15, 19, 45, 0, tzinfo=timezone.utc),
            "description": "Marcus Vance and Julian Thorne meet in person at Warehouse Dock 9.",
            "location_id": "L-001",
            "case_id": "CASE-001",
            "source_id": "SRC-004",
            "participants": [
                {"entity_id": "P-001", "role": "ATTENDEE"},
                {"entity_id": "P-004", "role": "ATTENDEE"},
                {"entity_id": "P-009", "role": "FACILITY_STAFF"},
                {"entity_id": "V-001", "role": "TRANSPORT"},
                {"entity_id": "L-001", "role": "VENUE"},
            ],
        },

        # Jan 17: Burner Ping
        {
            "id": "EVT-005",
            "event_type": "DEVICE_PING",
            "timestamp": datetime(2026, 1, 17, 18, 30, 0, tzinfo=timezone.utc),
            "description": "Burner phone PH-002 registered on cellular tower adjacent to Dock 9.",
            "location_id": "L-001",
            "case_id": "CASE-001",
            "source_id": "SRC-018",
            "participants": [
                {"entity_id": "PH-002", "role": "DEVICE"},
                {"entity_id": "L-001", "role": "CELL_TOWER_ZONE"},
            ],
        },

        # PATTERN 3 - SEQUENCE STEP 3: Jan 20 Transaction
        {
            "id": "EVT-006",
            "event_type": "TRANSACTION",
            "timestamp": datetime(2026, 1, 20, 11, 30, 0, tzinfo=timezone.utc),
            "description": "Account A-001 executes wire transfer of $250,000 to Barclays Escrow A-003, initiated by Julian Thorne.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-005",
            "participants": [
                {"entity_id": "A-001", "role": "SOURCE_ACCOUNT"},
                {"entity_id": "A-003", "role": "DESTINATION_ACCOUNT"},
                {"entity_id": "P-004", "role": "AUTHORIZER"},
            ],
        },

        # Jan 21: Air Cargo Arrival
        {
            "id": "EVT-007",
            "event_type": "CARGO_ARRIVAL",
            "timestamp": datetime(2026, 1, 21, 15, 0, 0, tzinfo=timezone.utc),
            "description": "Vanguard Trade shipment cleared by Amira Patel at Gateway Airport Terminal 4.",
            "location_id": "L-004",
            "case_id": "CASE-001",
            "source_id": "SRC-020",
            "participants": [
                {"entity_id": "P-010", "role": "CUSTOMS_BROKER"},
                {"entity_id": "ORG-003", "role": "CONSIGNEE"},
                {"entity_id": "V-003", "role": "TRANSPORT"},
                {"entity_id": "L-004", "role": "PORT_OF_ENTRY"},
            ],
        },

        # Jan 25: Private Club Meeting
        {
            "id": "EVT-008",
            "event_type": "MEETING",
            "timestamp": datetime(2026, 1, 25, 20, 0, 0, tzinfo=timezone.utc),
            "description": "Marcus Vance and Clara Bennett hold private consultation at Grand Oak Club Lounge.",
            "location_id": "L-003",
            "case_id": "CASE-001",
            "source_id": "SRC-004",
            "participants": [
                {"entity_id": "P-001", "role": "CLIENT"},
                {"entity_id": "P-008", "role": "COUNSEL"},
                {"entity_id": "L-003", "role": "VENUE"},
            ],
        },

        # Jan 29: Physical Search & Device Seizure
        {
            "id": "EVT-009",
            "event_type": "SEARCH_OPERATION",
            "timestamp": datetime(2026, 1, 29, 11, 0, 0, tzinfo=timezone.utc),
            "description": "Law enforcement search of Warehouse Dock 9; seizure of encrypted ThinkPad DEV-001.",
            "location_id": "L-001",
            "case_id": "CASE-001",
            "source_id": "SRC-010",
            "participants": [
                {"entity_id": "DEV-001", "role": "SEIZED_PROPERTY"},
                {"entity_id": "P-009", "role": "WITNESS"},
                {"entity_id": "L-001", "role": "LOCATION"},
            ],
        },

        # Jan 31: Payroll Run
        {
            "id": "EVT-010",
            "event_type": "TRANSACTION",
            "timestamp": datetime(2026, 1, 31, 17, 0, 0, tzinfo=timezone.utc),
            "description": "Routine monthly payroll execution from Signature Trust Account A-004.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-024",
            "participants": [
                {"entity_id": "A-004", "role": "DISBURSING_ACCOUNT"},
                {"entity_id": "ORG-002", "role": "EMPLOYER"},
            ],
        },

        # Feb 2: Digital Forensics Review
        {
            "id": "EVT-011",
            "event_type": "FORENSIC_EXTRACTION",
            "timestamp": datetime(2026, 2, 2, 14, 0, 0, tzinfo=timezone.utc),
            "description": "Video logs extracted from CCTV DVR server DEV-003.",
            "location_id": "L-001",
            "case_id": "CASE-001",
            "source_id": "SRC-023",
            "participants": [
                {"entity_id": "DEV-003", "role": "SOURCE_HARDWARE"},
                {"entity_id": "L-001", "role": "LOCATION"},
            ],
        },

        # PATTERN 4 (Feb Expansion): Feb 4 Bank Mandate Audit
        {
            "id": "EVT-012",
            "event_type": "FORENSIC_AUDIT",
            "timestamp": datetime(2026, 2, 4, 11, 45, 0, tzinfo=timezone.utc),
            "description": "Financial subpoena reveals joint mandate of Marcus Vance and Julian Thorne on Account A-001.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-011",
            "participants": [
                {"entity_id": "A-001", "role": "AUDITED_ACCOUNT"},
                {"entity_id": "P-001", "role": "BENEFICIAL_OWNER"},
                {"entity_id": "P-004", "role": "SIGNATORY"},
            ],
        },

        # Feb 12: Apex Tower Meeting
        {
            "id": "EVT-013",
            "event_type": "MEETING",
            "timestamp": datetime(2026, 2, 12, 14, 15, 0, tzinfo=timezone.utc),
            "description": "Julian Thorne meets Elena Rostova at Apex Financial Tower Suite 4200.",
            "location_id": "L-002",
            "case_id": "CASE-002",
            "source_id": "SRC-013",
            "participants": [
                {"entity_id": "P-004", "role": "ATTENDEE"},
                {"entity_id": "P-003", "role": "ATTENDEE"},
                {"entity_id": "L-002", "role": "VENUE"},
            ],
        },

        # Feb 18: Major Offshore Wire
        {
            "id": "EVT-014",
            "event_type": "TRANSACTION",
            "timestamp": datetime(2026, 2, 18, 14, 0, 0, tzinfo=timezone.utc),
            "description": "SWIFT wire transfer of $500,000 from Chase A-001 to HSBC Hong Kong A-002.",
            "location_id": None,
            "case_id": "CASE-002",
            "source_id": "SRC-012",
            "participants": [
                {"entity_id": "A-001", "role": "ORIGINATING_ACCOUNT"},
                {"entity_id": "A-002", "role": "BENEFICIARY_ACCOUNT"},
                {"entity_id": "ORG-001", "role": "BENEFICIARY_ENTITY"},
            ],
        },

        # Feb 25: Interim Report
        {
            "id": "EVT-015",
            "event_type": "INTELLIGENCE_BRIEFING",
            "timestamp": datetime(2026, 2, 25, 18, 0, 0, tzinfo=timezone.utc),
            "description": "Investigators summarize expansion from logistics into structured international financial vehicles.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-014",
            "participants": [
                {"entity_id": "P-001", "role": "SUBJECT"},
                {"entity_id": "P-004", "role": "FACILITATOR"},
                {"entity_id": "ORG-001", "role": "TARGET_ENTITY"},
            ],
        },

        # PATTERN 4 (March Expansion): March 1 Secondary Case Opening
        {
            "id": "EVT-016",
            "event_type": "CASE_OPENED",
            "timestamp": datetime(2026, 3, 1, 9, 15, 0, tzinfo=timezone.utc),
            "description": "CASE-002 (Meridian Financial Link) formally initiated to investigate Apex Holdings conduits.",
            "location_id": None,
            "case_id": "CASE-002",
            "source_id": "SRC-017",
            "participants": [
                {"entity_id": "CASE-ENT-002", "role": "NEW_CASE"},
                {"entity_id": "ORG-001", "role": "PRIMARY_SUBJECT"},
            ],
        },

        # March 3: Whistleblower Interview
        {
            "id": "EVT-017",
            "event_type": "INTERVIEW",
            "timestamp": datetime(2026, 3, 3, 13, 0, 0, tzinfo=timezone.utc),
            "description": "Sophia Chen interviewed by financial enforcement agents regarding unlogged asset conduits.",
            "location_id": "L-002",
            "case_id": "CASE-002",
            "source_id": "SRC-015",
            "participants": [
                {"entity_id": "P-005", "role": "WITNESS"},
                {"entity_id": "ORG-001", "role": "EMPLOYER"},
                {"entity_id": "L-002", "role": "LOCATION"},
            ],
        },

        # March 10: Barclays Escrow Release
        {
            "id": "EVT-018",
            "event_type": "TRANSACTION",
            "timestamp": datetime(2026, 3, 10, 15, 30, 0, tzinfo=timezone.utc),
            "description": "$1.2M escrow disbursement from Barclays A-003 to Swiss Trust accounts in Zurich.",
            "location_id": "L-005",
            "case_id": "CASE-002",
            "source_id": "SRC-016",
            "participants": [
                {"entity_id": "A-003", "role": "ESCROW_ACCOUNT"},
                {"entity_id": "P-003", "role": "TRUSTEE"},
                {"entity_id": "P-013", "role": "SWISS_ADMINISTRATOR"},
                {"entity_id": "L-005", "role": "SETTLEMENT_HUB"},
            ],
        },

        # March 11: Hardware Wallet Inspection
        {
            "id": "EVT-019",
            "event_type": "FORENSIC_EXTRACTION",
            "timestamp": datetime(2026, 3, 11, 16, 0, 0, tzinfo=timezone.utc),
            "description": "Forensics team identifies Ledger DEV-002 as multi-sig keyholder for offshore wire authentication.",
            "location_id": "L-005",
            "case_id": "CASE-002",
            "source_id": "SRC-016",
            "participants": [
                {"entity_id": "DEV-002", "role": "CRYPTO_DEVICE"},
                {"entity_id": "A-002", "role": "ASSOCIATED_ACCOUNT"},
            ],
        },

        # March 15: Cross-Case Connection Established
        {
            "id": "EVT-020",
            "event_type": "INTELLIGENCE_BRIEFING",
            "timestamp": datetime(2026, 3, 15, 9, 0, 0, tzinfo=timezone.utc),
            "description": "Formal linkage of Julian Thorne (P-004) between CASE-001 and CASE-002 approved by lead prosecutors.",
            "location_id": None,
            "case_id": "CASE-002",
            "source_id": "SRC-017",
            "participants": [
                {"entity_id": "P-004", "role": "CROSS_CASE_SUBJECT"},
                {"entity_id": "CASE-ENT-001", "role": "ORIGIN_CASE"},
                {"entity_id": "CASE-ENT-002", "role": "TARGET_CASE"},
            ],
        },

        # March 18: Swiss Legal Mutual Assistance
        {
            "id": "EVT-021",
            "event_type": "LEGAL_REQUEST",
            "timestamp": datetime(2026, 3, 18, 10, 0, 0, tzinfo=timezone.utc),
            "description": "Mutual Legal Assistance Treaty (MLAT) request sent to Swiss Federal Office of Justice regarding Zurich Vaults.",
            "location_id": "L-005",
            "case_id": "CASE-002",
            "source_id": "SRC-016",
            "participants": [
                {"entity_id": "L-005", "role": "JURISDICTION"},
                {"entity_id": "ORG-001", "role": "TARGET_CORPORATION"},
                {"entity_id": "P-013", "role": "NAMED_OFFICER"},
            ],
        },

        # March 20: Comprehensive Case Review
        {
            "id": "EVT-022",
            "event_type": "CASE_REVIEW",
            "timestamp": datetime(2026, 3, 20, 16, 30, 0, tzinfo=timezone.utc),
            "description": "Lead investigator review of Operation Meridian complete graph and timeline evidence.",
            "location_id": None,
            "case_id": "CASE-001",
            "source_id": "SRC-025",
            "participants": [
                {"entity_id": "P-001", "role": "PRIMARY_SUSPECT"},
                {"entity_id": "P-004", "role": "CO_CONSPIRATOR"},
            ],
        },
    ]

    return {
        "cases": cases,
        "entities": entities,
        "case_entities": case_entities,
        "sources": sources,
        "evidence": evidence,
        "relationships": relationships,
        "events": events,
    }
